# Generated by Django 5.1.1 on 2024-09-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=8)),
                ('date', models.DateField()),
                ('pos_sentiment', models.FloatField(default=0.0, null=True)),
                ('neg_sentiment', models.FloatField(default=0.0, null=True)),
            ],
        ),
    ]
