# Generated by Django 5.1.1 on 2024-09-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=8)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('pos_score', models.IntegerField(null=True)),
                ('neg_score', models.IntegerField(null=True)),
                ('overall_rating', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=8)),
                ('date', models.DateField()),
                ('overall_rating', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
