# Generated by Django 5.1.1 on 2024-10-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_app', '0002_articles_summaries_delete_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='neg_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='overall_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='pos_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='summaries',
            name='overall_rating',
            field=models.FloatField(null=True),
        ),
    ]
